[package]
name = "toytcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = { version = "0.31.0", features=["std"] }
local-ip-address = "0.4.9"
anyhow = "1.0.66"
rand = "0.8.5"
ctrlc= "3.1"
